platform :ios, '10.0'
use_frameworks!

target 'BLZFirebaseAuthenticator_Example' do
  pod 'BLZFirebaseAuthenticator', :path => '../'

  target 'BLZFirebaseAuthenticator_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
